### ISSUE TITLE
DAB File support

### ISSUE THREAD

**Issue by vegasbrianc** [francescou/docker-compose-search#2]
Since Docker introduced DAB files what do you think about having an option to search for DAB files as well.?

**Comment by francescou** [comment]
Hi, yes I plan to add support for DAB files in the near future.

**Comment by francescou** [comment]
The problem is that there are only few examples of _.dsb_/_.dab_ files on github.

Otherwise, a solution could be to convert the docker-compose.yml files to .dab but the converter provided by docker-compose 1.8.0rc1 requires you to pull the images for all the services

**Comment by vegasbrianc** [comment]
You are absolutely correct. I was only able to find to instances of a dsb file. However, this is a beta feature which should be available with the next release. So I expect more files to come or maybe not.
